Anno:
  TestProject:
    Analyse:
      Active: 2
      Calculators:
        1:
          Colour: [0, 0, 0]
          FirstWindow: 2
          Name: Calculator 1
          Operation: '-'
          SecondWindow: 1
          Show: 2
        2:
          Colour: [0, 255, 0]
          FirstWindow: 2
          Name: Calculator 2
          Operation: +
          SecondWindow: 1
          Show: 2
      Pause: 0.1 s
      ScanLabel: Scannumber
      ScanValue: 1
      ScanValueDifference: 1
      Scans: 10
      ShowPlot: 2
      Windows:
        1:
          Channel: A
          Colour: [255, 170, 0]
          Length: '100'
          Show: 2
          Start: '500'
        2:
          Channel: A
          Colour: [0, 170, 0]
          Length: '100'
          Show: 2
          Start: '100'
    Average: {Blocks: 10, Pause: 0.03 s, Store: 0}
    Channels:
      A: {Active: 2, CouplingType: DC, Range: 1 V}
      B: {Active: 2, CouplingType: DC, Range: 1 V}
      C: {Active: 0, CouplingType: DC, Range: 1 V}
      D: {Active: 0, CouplingType: DC, Range: 1 V}
    Metadata: {Importfile: 'C:\Users\annot\Documents\eEDM\GitHubTest\PicoscopeData\DefaultData_start_time_metadata.yml'}
    Plot: {Show: 2}
    Save: {Autosave: Every scope average, Channels: All Activated, Filename: DefaultData,
      Folder: 'C:\Users\annot\Documents\eEDM\GitHubTest\PicoscopeData'}
    Time: {Blocklength: 1006992 nanosecond, Resolution: 12BIT, Samples: 1000, Timebase: 66,
      Timestep: 1008 ns, maxADC: 32767}
    Trigger: {Active: 2, Auto: 10 ms, Channel: A, Delay: 0, Level: 200 mV, Position: 500,
      Show: 0, Type: Rising}
    User: {Fontsize: '12'}
AutoSaveDefaultUser:
  DefaultProject:
    Analyse:
      Active: 0
      Calculators:
        1:
          Colour: [0, 0, 0]
          FirstWindow: 2
          Name: Calculator 1
          Operation: '-'
          SecondWindow: 1
          Show: 2
        2:
          Colour: [0, 255, 0]
          FirstWindow: 2
          Name: Calculator 2
          Operation: +
          SecondWindow: 1
          Show: 2
      Pause: 1 s
      ScanLabel: Scannumber
      ScanValue: 1
      ScanValueDifference: 1
      Scans: 10
      ShowPlot: 0
      Windows:
        1:
          Channel: A
          Colour: [255, 170, 0]
          Length: '1000'
          Show: 2
          Start: '5000'
        2:
          Channel: A
          Colour: [0, 170, 0]
          Length: '1000'
          Show: 2
          Start: '2000'
    Average: {Blocks: 10, Pause: 0.1 s, Store: 0}
    Channels:
      A: {Active: 2, CouplingType: DC, Range: 1 V}
      B: {Active: 2, CouplingType: DC, Range: 1 V}
      C: {Active: 0, CouplingType: DC, Range: 1 V}
      D: {Active: 0, CouplingType: DC, Range: 1 V}
    Metadata: {Importfile: 'C:\Users\annot\Documents\eEDM\GitHubTest\PicoscopeData\DefaultData_start_time_metadata.yml'}
    Plot: {Show: 2}
    Save: {Autosave: Every scope average, Channels: All Activated, Filename: DefaultData,
      Folder: 'C:\Users\annot\Documents\eEDM\GitHubTest\PicoscopeData'}
    Time: {Blocklength: 959904 nanosecond, Resolution: 12BIT, Samples: 10000, Timebase: 9,
      Timestep: 96 ns, maxADC: 32767}
    Trigger: {Active: 2, Auto: 100 ms, Channel: A, Delay: 0, Level: 200 mV, Position: 5000,
      Show: 0, Type: Rising}
    User: {Fontsize: '11'}
DefaultUser:
  DefaultProject:
    Analyse:
      Active: 0
      Calculators:
        1:
          Colour: [0, 0, 0]
          FirstWindow: 2
          Name: Calculator 1
          Operation: '-'
          SecondWindow: 1
          Show: 2
      Pause: 1 s
      ScanLabel: Scannumber
      ScanValue: 1
      ScanValueDifference: 1
      Scans: 10
      ShowPlot: 0
      Windows:
        1:
          Channel: A
          Colour: [255, 170, 0]
          Length: 500
          Show: 0
          Start: 20
        2:
          Channel: A
          Colour: [0, 170, 0]
          Length: 500
          Show: 0
          Start: 20
    Average: {Blocks: 10, Pause: 0.1 s, Store: 0}
    Channels:
      A: {Active: 2, CouplingType: DC, Range: 1 V}
      B: {Active: 2, CouplingType: DC, Range: 1 V}
      C: {Active: 0, CouplingType: DC, Range: 1 V}
      D: {Active: 0, CouplingType: DC, Range: 1 V}
    Metadata: {Importfile: BaseDirectory\PicoscopeData\Date\DefaultData_Date_scan_number_metadata.yml}
    Plot: {Show: 2}
    Save: {Autosave: Never, Channels: All Activated, Filename: DefaultData, Folder: BaseDirectory\PicoscopeData}
    Time: {Blocklength: 959904 nanosecond, Resolution: 12BIT, Samples: 10000, Timebase: 9,
      Timestep: 96 ns, maxADC: 32767}
    Trigger: {Active: 2, Auto: 100 ms, Channel: A, Delay: 0, Level: 200 mV, Position: 5000,
      Show: 0, Type: Rising}
    User: {Fontsize: '11'}
PreviousUser: {Name: Anno, Project: TestProject}
