AutoSaveDefaultUser:
  DefaultProject:
    Analyse:
      Active: 0
      Calculators:
        1:
          Colour:
          - 0
          - 0
          - 0
          FirstWindow: 1
          Name: Calculator 1
          Operation: '-'
          SecondWindow: 2
          Show: 2
        2:
          Colour:
          - 214
          - 1
          - 224
          FirstWindow: 3
          Name: fs-laser
          Operation: '-'
          SecondWindow: 4
          Show: 2
      Pause: 1 ms
      ScanLabel: Scannumber
      ScanValue: 1.0
      ScanValueDifference: 1.0
      Scans: 10
      ShowPlot: 2
      Windows:
        1:
          Channel: B
          Colour:
          - 0
          - 170
          - 0
          Length: 11
          Show: 2
          Start: 303
        2:
          Channel: B
          Colour:
          - 170
          - 0
          - 255
          Length: 0
          Show: 2
          Start: 1999
        3:
          Channel: B
          Colour:
          - 47
          - 3
          - 168
          Length: 11
          Show: 2
          Start: 303
        4:
          Channel: B
          Colour:
          - 192
          - 179
          - 10
          Length: 200
          Show: 2
          Start: 0
    Average:
      Blocks: 10
      Pause: 10 ms
      Store: 0
    Channels:
      A:
        Active: 2
        CouplingType: DC
        Name: PMT
        Range: 200 mV
      B:
        Active: 2
        CouplingType: DC
        Name: fs-laser
        Range: 1 V
      C:
        Active: 0
        CouplingType: DC
        Name: C
        Range: 1 V
      D:
        Active: 0
        CouplingType: DC
        Name: D
        Range: 1 V
    Delay:
      Active: 1
      Connectors:
        A:
          Delay: 1 ms
          From: B
        B:
          Delay: 0.064 s
          From: D
        C:
          Delay: 3 ms
          From: D
        D:
          Delay: 99.98 ms
          From: T0
      Load: 50 Ohm
      Port: COM3
      TriggerEdge: Rising
      TriggerLevel: 1 V
      TriggerLoad: 50 Ohm
      TriggerMode: External
      TriggerRate: 10 Hz
      Type: TTL
    Measurement time: '2019-07-11 13:59:12.479405'
    Metadata:
      Importfile: C:\Users\EDGE\Documents\Maarten\PicoscopeData\DefaultData_start_time_metadata.yml
    Plot:
      Show: 2
    Save:
      Autosave: Never
      Channels: All Activated
      Filename: Data
      Folder: C:\Users\EDGE\Documents\Maarten\PicoscopeData
    Time:
      Blocklength: 31.984 us
      Resolution: 12BIT
      Samples: 2000
      Timebase: 4
      Timestep: 16 ns
      maxADC: 32767
    Trigger:
      Active: 2
      Auto: 1000 ms
      Channel: External
      Delay: 0
      Level: 1 V
      Position: 0
      Show: 0
      Type: Rising
    User:
      Fontsize: 9
DefaultUser:
  DefaultProject:
    Analyse:
      Active: 0
      Calculators:
        1:
          Colour:
          - 0
          - 0
          - 0
          FirstWindow: 2
          Name: Calculator 1
          Operation: '-'
          SecondWindow: 1
          Show: 2
      Pause: 1 s
      ScanLabel: Scannumber
      ScanValue: 1
      ScanValueDifference: 1
      Scans: 10
      ShowPlot: 0
      Windows:
        1:
          Channel: A
          Colour:
          - 255
          - 170
          - 0
          Length: 500
          Show: 0
          Start: 500
        2:
          Channel: A
          Colour:
          - 0
          - 170
          - 0
          Length: 500
          Show: 0
          Start: 20
    Average:
      Blocks: 10
      Pause: 0.1 s
      Store: 0
    Channels:
      A:
        Active: 2
        CouplingType: DC
        Name: A
        Range: 1 V
      B:
        Active: 2
        CouplingType: DC
        Name: B
        Range: 1 V
      C:
        Active: 0
        CouplingType: DC
        Name: C
        Range: 1 V
      D:
        Active: 0
        CouplingType: DC
        Name: D
        Range: 1 V
    Delay:
      Active: 0
      Connectors:
        A:
          Delay: 1 ms
          From: T0
        B:
          Delay: 2 ms
          From: T0
        C:
          Delay: 3 ms
          From: T0
        D:
          Delay: 4 ms
          From: T0
      Load: 50 Ohm
      Port: COM3
      TriggerEdge: Rising
      TriggerLevel: 1 V
      TriggerLoad: 50 Ohm
      TriggerMode: Internal
      TriggerRate: 10 Hz
      Type: TTL
    Metadata:
      Importfile: BaseDirectory\PicoscopeData\Date\DefaultData_Date_scan_number_metadata.yml
    Plot:
      Show: 2
    Save:
      Autosave: Never
      Channels: All Activated
      Filename: DefaultData
      Folder: BaseDirectory\PicoscopeData
    Time:
      Blocklength: 959904 ns
      Resolution: 12BIT
      Samples: 10000
      Timebase: 9
      Timestep: 96 ns
      maxADC: 32767
    Trigger:
      Active: 2
      Auto: 100 ms
      Channel: A
      Delay: 0
      Level: 200 mV
      Position: 5000
      Show: 0
      Type: Rising
    User:
      Fontsize: '9'
MaartenMooij:
  First TOF BaF:
    Analyse:
      Active: 2
      Calculators:
        1:
          Colour:
          - 0
          - 0
          - 0
          FirstWindow: 1
          Name: H2O
          Operation: '-'
          SecondWindow: 2
          Show: 2
        2:
          Colour:
          - 214
          - 1
          - 224
          FirstWindow: 3
          Name: fs-laser
          Operation: '-'
          SecondWindow: 4
          Show: 2
        3:
          Colour:
          - 15
          - 208
          - 139
          FirstWindow: 5
          Name: Ne
          Operation: '-'
          SecondWindow: 2
          Show: 2
        4:
          Colour:
          - 224
          - 12
          - 210
          FirstWindow: 6
          Name: SF5
          Operation: '-'
          SecondWindow: 4
          Show: 0
        5:
          Colour:
          - 244
          - 72
          - 252
          FirstWindow: 7
          Name: Ba
          Operation: '-'
          SecondWindow: 2
          Show: 2
        6:
          Colour:
          - 164
          - 97
          - 138
          FirstWindow: 8
          Name: BaF
          Operation: '-'
          SecondWindow: 2
          Show: 0
        7:
          Colour:
          - 180
          - 101
          - 217
          FirstWindow: 9
          Name: SF3
          Operation: '-'
          SecondWindow: 2
          Show: 0
      Pause: 10 ms
      ScanLabel: face scan delay generator
      ScanValue: 1.0
      ScanValueDifference: 1.0
      Scans: 1000
      ShowPlot: 2
      Windows:
        1:
          Channel: A
          Colour:
          - 0
          - 0
          - 0
          Length: 46
          Show: 2
          Start: 2339
        2:
          Channel: A
          Colour:
          - 170
          - 0
          - 255
          Length: '400'
          Show: 2
          Start: '0'
        3:
          Channel: B
          Colour:
          - 47
          - 3
          - 168
          Length: 52
          Show: 2
          Start: 1195
        4:
          Channel: B
          Colour:
          - 192
          - 179
          - 10
          Length: '400'
          Show: 2
          Start: 0
        5:
          Channel: A
          Colour:
          - 139
          - 39
          - 163
          Length: 38
          Show: 2
          Start: '2400'
        6:
          Channel: A
          Colour:
          - 19
          - 28
          - 132
          Length: 800
          Show: 0
          Start: 0
        7:
          Channel: A
          Colour:
          - 196
          - 106
          - 153
          Length: 119
          Show: 2
          Start: 4251
        8:
          Channel: A
          Colour:
          - 25
          - 53
          - 199
          Length: 800
          Show: 2
          Start: 0
        9:
          Channel: A
          Colour:
          - 147
          - 244
          - 115
          Length: 800
          Show: 0
          Start: 0
    Average:
      Blocks: 20
      Pause: 0 ms
      Store: 0
    Channels:
      A:
        Active: 2
        CouplingType: DC
        Name: PMT
        Range: 50 mV
      B:
        Active: 2
        CouplingType: DC
        Name: fs-laser
        Range: 2 V
      C:
        Active: 0
        CouplingType: DC
        Name: C
        Range: 1 V
      D:
        Active: 0
        CouplingType: DC
        Name: D
        Range: 1 V
    Delay:
      Active: 2
      Connectors:
        A:
          Delay: 1 ms
          From: B
        B:
          Delay: 0.064 s
          From: D
        C:
          Delay: 5 ms
          From: D
        D:
          Delay: 99.98 ms
          From: T0
      Load: 50 Ohm
      Port: COM3
      TriggerEdge: Rising
      TriggerLevel: 1 V
      TriggerLoad: 50 Ohm
      TriggerMode: External
      TriggerRate: 10 Hz
      Type: TTL
    Measurement time: '2019-07-12 17:54:27.023508'
    Metadata:
      Importfile: C:\Users\EDGE\Documents\Maarten\PicoscopeData\DefaultData_start_time_metadata.yml
    Plot:
      Show: 2
    Save:
      Autosave: Never
      Channels: All Activated
      Filename: Data
      Folder: C:\Users\EDGE\Documents\Maarten\PicoscopeData
    Time:
      Blocklength: 39.996 us
      Resolution: 12BIT
      Samples: 10000
      Timebase: 2
      Timestep: 4 ns
      maxADC: 32767
    Trigger:
      Active: 2
      Auto: 2000 ms
      Channel: External
      Delay: 0
      Level: 1 V
      Position: 0
      Show: 2
      Type: Rising
    User:
      Fontsize: 9
  Project:
    Analyse:
      Active: 0
      Calculators:
        1:
          Colour:
          - 0
          - 0
          - 0
          FirstWindow: 1
          Name: Calculator 1
          Operation: '-'
          SecondWindow: 2
          Show: 2
        2:
          Colour:
          - 214
          - 1
          - 224
          FirstWindow: 3
          Name: fs-laser
          Operation: '-'
          SecondWindow: 4
          Show: 2
      Pause: 1 ms
      ScanLabel: Scannumber
      ScanValue: 1.0
      ScanValueDifference: 1.0
      Scans: 10
      ShowPlot: 2
      Windows:
        1:
          Channel: B
          Colour:
          - 0
          - 170
          - 0
          Length: 11
          Show: 2
          Start: 303
        2:
          Channel: B
          Colour:
          - 170
          - 0
          - 255
          Length: 0
          Show: 2
          Start: 1999
        3:
          Channel: B
          Colour:
          - 47
          - 3
          - 168
          Length: 11
          Show: 2
          Start: 303
        4:
          Channel: B
          Colour:
          - 192
          - 179
          - 10
          Length: 200
          Show: 2
          Start: 0
    Average:
      Blocks: 10
      Pause: 10 ms
      Store: 0
    Channels:
      A:
        Active: 2
        CouplingType: DC
        Name: PMT
        Range: 200 mV
      B:
        Active: 2
        CouplingType: DC
        Name: fs-laser
        Range: 1 V
      C:
        Active: 0
        CouplingType: DC
        Name: C
        Range: 1 V
      D:
        Active: 0
        CouplingType: DC
        Name: D
        Range: 1 V
    Delay:
      Active: 1
      Connectors:
        A:
          Delay: 1 ms
          From: B
        B:
          Delay: 0.064 s
          From: D
        C:
          Delay: 3 ms
          From: D
        D:
          Delay: 99.98 ms
          From: T0
      Load: 50 Ohm
      Port: COM3
      TriggerEdge: Rising
      TriggerLevel: 1 V
      TriggerLoad: 50 Ohm
      TriggerMode: External
      TriggerRate: 10 Hz
      Type: TTL
    Measurement time: '2019-07-11 13:59:12.479405'
    Metadata:
      Importfile: C:\Users\EDGE\Documents\Maarten\PicoscopeData\DefaultData_start_time_metadata.yml
    Plot:
      Show: 2
    Save:
      Autosave: Never
      Channels: All Activated
      Filename: Data
      Folder: C:\Users\EDGE\Documents\Maarten\PicoscopeData
    Time:
      Blocklength: 31.984 us
      Resolution: 12BIT
      Samples: 2000
      Timebase: 4
      Timestep: 16 ns
      maxADC: 32767
    Trigger:
      Active: 2
      Auto: 1000 ms
      Channel: External
      Delay: 0
      Level: 1 V
      Position: 0
      Show: 0
      Type: Rising
    User:
      Fontsize: 9
PreviousUser:
  Name: MaartenMooij
  Project: First TOF BaF
