# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1795, 548)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.start_button.setFont(font)
        self.start_button.setObjectName("start_button")
        self.horizontalLayout_2.addWidget(self.start_button)
        self.continuously_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.continuously_button.setFont(font)
        self.continuously_button.setObjectName("continuously_button")
        self.horizontalLayout_2.addWidget(self.continuously_button)
        self.pause_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pause_button.setFont(font)
        self.pause_button.setObjectName("pause_button")
        self.horizontalLayout_2.addWidget(self.pause_button)
        self.stop_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.stop_button.setFont(font)
        self.stop_button.setObjectName("stop_button")
        self.horizontalLayout_2.addWidget(self.stop_button)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 4, 0, 2, 1)
        self.Messages = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Messages.sizePolicy().hasHeightForWidth())
        self.Messages.setSizePolicy(sizePolicy)
        self.Messages.setMaximumSize(QtCore.QSize(16777215, 100))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(237, 237, 237))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(237, 237, 237))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.Messages.setPalette(palette)
        self.Messages.setObjectName("Messages")
        self.gridLayout_3.addWidget(self.Messages, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 500))
        self.tabWidget.setObjectName("tabWidget")
        self.User = QtWidgets.QWidget()
        self.User.setObjectName("User")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.User)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.Save_personal_settingsL = QtWidgets.QLabel(self.User)
        self.Save_personal_settingsL.setObjectName("Save_personal_settingsL")
        self.gridLayout_7.addWidget(self.Save_personal_settingsL, 1, 3, 1, 1)
        self.ProjectL = QtWidgets.QLabel(self.User)
        self.ProjectL.setObjectName("ProjectL")
        self.gridLayout_7.addWidget(self.ProjectL, 2, 0, 1, 1)
        self.Project = QtWidgets.QLineEdit(self.User)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Project.sizePolicy().hasHeightForWidth())
        self.Project.setSizePolicy(sizePolicy)
        self.Project.setMinimumSize(QtCore.QSize(200, 30))
        self.Project.setMaximumSize(QtCore.QSize(200, 30))
        self.Project.setText("")
        self.Project.setObjectName("Project")
        self.gridLayout_7.addWidget(self.Project, 2, 1, 1, 1)
        self.NameL = QtWidgets.QLabel(self.User)
        self.NameL.setObjectName("NameL")
        self.gridLayout_7.addWidget(self.NameL, 1, 0, 1, 1)
        self.FontsizeL = QtWidgets.QLabel(self.User)
        self.FontsizeL.setObjectName("FontsizeL")
        self.gridLayout_7.addWidget(self.FontsizeL, 3, 0, 1, 1)
        self.Name = QtWidgets.QLineEdit(self.User)
        self.Name.setMinimumSize(QtCore.QSize(0, 30))
        self.Name.setMaximumSize(QtCore.QSize(200, 30))
        self.Name.setText("")
        self.Name.setObjectName("Name")
        self.gridLayout_7.addWidget(self.Name, 1, 1, 1, 1)
        self.Save_personal_settings_button = QtWidgets.QPushButton(self.User)
        self.Save_personal_settings_button.setMinimumSize(QtCore.QSize(0, 30))
        self.Save_personal_settings_button.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Save_personal_settings_button.setObjectName("Save_personal_settings_button")
        self.gridLayout_7.addWidget(self.Save_personal_settings_button, 1, 5, 1, 1)
        self.Fontsize = QtWidgets.QSpinBox(self.User)
        self.Fontsize.setMinimumSize(QtCore.QSize(0, 30))
        self.Fontsize.setMaximumSize(QtCore.QSize(200, 30))
        self.Fontsize.setMinimum(8)
        self.Fontsize.setMaximum(20)
        self.Fontsize.setProperty("value", 11)
        self.Fontsize.setObjectName("Fontsize")
        self.gridLayout_7.addWidget(self.Fontsize, 3, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem, 1, 2, 1, 1)
        self.Import_from_metadataL = QtWidgets.QLabel(self.User)
        self.Import_from_metadataL.setObjectName("Import_from_metadataL")
        self.gridLayout_7.addWidget(self.Import_from_metadataL, 3, 3, 1, 1)
        self.Metadata_input = QtWidgets.QLineEdit(self.User)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Metadata_input.sizePolicy().hasHeightForWidth())
        self.Metadata_input.setSizePolicy(sizePolicy)
        self.Metadata_input.setMinimumSize(QtCore.QSize(100, 30))
        self.Metadata_input.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Metadata_input.setObjectName("Metadata_input")
        self.gridLayout_7.addWidget(self.Metadata_input, 3, 4, 1, 1)
        self.Import_personal_settings_metadata_button = QtWidgets.QPushButton(self.User)
        self.Import_personal_settings_metadata_button.setMinimumSize(QtCore.QSize(0, 30))
        self.Import_personal_settings_metadata_button.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Import_personal_settings_metadata_button.setObjectName("Import_personal_settings_metadata_button")
        self.gridLayout_7.addWidget(self.Import_personal_settings_metadata_button, 3, 5, 1, 1)
        self.Load_personal_settings_button = QtWidgets.QPushButton(self.User)
        self.Load_personal_settings_button.setMinimumSize(QtCore.QSize(0, 30))
        self.Load_personal_settings_button.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Load_personal_settings_button.setDefault(False)
        self.Load_personal_settings_button.setObjectName("Load_personal_settings_button")
        self.gridLayout_7.addWidget(self.Load_personal_settings_button, 2, 5, 1, 1)
        self.Load_personal_settingsL = QtWidgets.QLabel(self.User)
        self.Load_personal_settingsL.setObjectName("Load_personal_settingsL")
        self.gridLayout_7.addWidget(self.Load_personal_settingsL, 2, 3, 1, 1)
        self.tabWidget.addTab(self.User, "")
        self.Save = QtWidgets.QWidget()
        self.Save.setObjectName("Save")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.Save)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.DirectoryL = QtWidgets.QLabel(self.Save)
        self.DirectoryL.setObjectName("DirectoryL")
        self.gridLayout_8.addWidget(self.DirectoryL, 0, 0, 1, 1)
        self.Filename = QtWidgets.QLineEdit(self.Save)
        self.Filename.setMinimumSize(QtCore.QSize(0, 30))
        self.Filename.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Filename.setText("")
        self.Filename.setObjectName("Filename")
        self.gridLayout_8.addWidget(self.Filename, 1, 3, 1, 1)
        self.FilenameL = QtWidgets.QLabel(self.Save)
        self.FilenameL.setObjectName("FilenameL")
        self.gridLayout_8.addWidget(self.FilenameL, 1, 0, 1, 1)
        self.Directory = QtWidgets.QLineEdit(self.Save)
        self.Directory.setMinimumSize(QtCore.QSize(0, 30))
        self.Directory.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Directory.setObjectName("Directory")
        self.gridLayout_8.addWidget(self.Directory, 0, 3, 1, 1)
        self.Autosave = QtWidgets.QComboBox(self.Save)
        self.Autosave.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Autosave.setObjectName("Autosave")
        self.Autosave.addItem("")
        self.Autosave.addItem("")
        self.Autosave.addItem("")
        self.gridLayout_8.addWidget(self.Autosave, 2, 3, 1, 1)
        self.AutosaveL = QtWidgets.QLabel(self.Save)
        self.AutosaveL.setObjectName("AutosaveL")
        self.gridLayout_8.addWidget(self.AutosaveL, 2, 0, 1, 1)
        self.tabWidget.addTab(self.Save, "")
        self.TimeSettings = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TimeSettings.sizePolicy().hasHeightForWidth())
        self.TimeSettings.setSizePolicy(sizePolicy)
        self.TimeSettings.setObjectName("TimeSettings")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.TimeSettings)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.Time = QtWidgets.QGroupBox(self.TimeSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Time.sizePolicy().hasHeightForWidth())
        self.Time.setSizePolicy(sizePolicy)
        self.Time.setObjectName("Time")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.Time)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.Timestep = QtWidgets.QTextBrowser(self.Time)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Timestep.sizePolicy().hasHeightForWidth())
        self.Timestep.setSizePolicy(sizePolicy)
        self.Timestep.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Timestep.setObjectName("Timestep")
        self.gridLayout_11.addWidget(self.Timestep, 1, 10, 1, 1)
        self.BlocklengthL = QtWidgets.QLabel(self.Time)
        self.BlocklengthL.setObjectName("BlocklengthL")
        self.gridLayout_11.addWidget(self.BlocklengthL, 1, 6, 1, 1)
        self.Blocklength = QtWidgets.QLineEdit(self.Time)
        self.Blocklength.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Blocklength.setText("")
        self.Blocklength.setObjectName("Blocklength")
        self.gridLayout_11.addWidget(self.Blocklength, 1, 7, 1, 1)
        self.ResolutionL = QtWidgets.QLabel(self.Time)
        self.ResolutionL.setObjectName("ResolutionL")
        self.gridLayout_11.addWidget(self.ResolutionL, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem1, 1, 5, 1, 1)
        self.Samples = QtWidgets.QLineEdit(self.Time)
        self.Samples.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Samples.setText("")
        self.Samples.setObjectName("Samples")
        self.gridLayout_11.addWidget(self.Samples, 1, 4, 1, 1)
        self.SamplesL = QtWidgets.QLabel(self.Time)
        self.SamplesL.setObjectName("SamplesL")
        self.gridLayout_11.addWidget(self.SamplesL, 1, 3, 1, 1)
        self.Resolution = QtWidgets.QComboBox(self.Time)
        self.Resolution.setMinimumSize(QtCore.QSize(100, 0))
        self.Resolution.setMaximumSize(QtCore.QSize(100, 30))
        self.Resolution.setObjectName("Resolution")
        self.Resolution.addItem("")
        self.Resolution.addItem("")
        self.Resolution.addItem("")
        self.Resolution.addItem("")
        self.Resolution.addItem("")
        self.gridLayout_11.addWidget(self.Resolution, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem2, 1, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem3, 1, 8, 1, 1)
        self.TimestepL = QtWidgets.QLabel(self.Time)
        self.TimestepL.setObjectName("TimestepL")
        self.gridLayout_11.addWidget(self.TimestepL, 1, 9, 1, 1)
        self.gridLayout_13.addWidget(self.Time, 0, 0, 1, 1)
        self.Trigger = QtWidgets.QGroupBox(self.TimeSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Trigger.sizePolicy().hasHeightForWidth())
        self.Trigger.setSizePolicy(sizePolicy)
        self.Trigger.setObjectName("Trigger")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.Trigger)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.TAtiveL_2 = QtWidgets.QLabel(self.Trigger)
        self.TAtiveL_2.setObjectName("TAtiveL_2")
        self.gridLayout_12.addWidget(self.TAtiveL_2, 1, 6, 1, 1)
        self.TShow = QtWidgets.QCheckBox(self.Trigger)
        self.TShow.setText("")
        self.TShow.setObjectName("TShow")
        self.gridLayout_12.addWidget(self.TShow, 1, 7, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem4, 1, 14, 1, 1)
        self.TChannelL_2 = QtWidgets.QLabel(self.Trigger)
        self.TChannelL_2.setObjectName("TChannelL_2")
        self.gridLayout_12.addWidget(self.TChannelL_2, 1, 12, 1, 1)
        self.TDelay = QtWidgets.QLineEdit(self.Trigger)
        self.TDelay.setMaximumSize(QtCore.QSize(16777215, 30))
        self.TDelay.setText("")
        self.TDelay.setObjectName("TDelay")
        self.gridLayout_12.addWidget(self.TDelay, 1, 19, 1, 1)
        self.TLevel = QtWidgets.QLineEdit(self.Trigger)
        self.TLevel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.TLevel.setText("")
        self.TLevel.setObjectName("TLevel")
        self.gridLayout_12.addWidget(self.TLevel, 1, 16, 1, 1)
        self.TPosition = QtWidgets.QLineEdit(self.Trigger)
        self.TPosition.setMaximumSize(QtCore.QSize(16777215, 30))
        self.TPosition.setText("")
        self.TPosition.setObjectName("TPosition")
        self.gridLayout_12.addWidget(self.TPosition, 1, 22, 1, 1)
        self.TSampleInWindowL = QtWidgets.QLabel(self.Trigger)
        self.TSampleInWindowL.setObjectName("TSampleInWindowL")
        self.gridLayout_12.addWidget(self.TSampleInWindowL, 1, 21, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem5, 1, 17, 1, 1)
        self.TAtiveL = QtWidgets.QLabel(self.Trigger)
        self.TAtiveL.setObjectName("TAtiveL")
        self.gridLayout_12.addWidget(self.TAtiveL, 1, 3, 1, 1)
        self.TChannel = QtWidgets.QComboBox(self.Trigger)
        self.TChannel.setMinimumSize(QtCore.QSize(100, 30))
        self.TChannel.setMaximumSize(QtCore.QSize(100, 30))
        self.TChannel.setObjectName("TChannel")
        self.TChannel.addItem("")
        self.TChannel.addItem("")
        self.TChannel.addItem("")
        self.TChannel.addItem("")
        self.TChannel.addItem("")
        self.gridLayout_12.addWidget(self.TChannel, 1, 10, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem6, 1, 11, 1, 1)
        self.TSamplesDelayedL = QtWidgets.QLabel(self.Trigger)
        self.TSamplesDelayedL.setObjectName("TSamplesDelayedL")
        self.gridLayout_12.addWidget(self.TSamplesDelayedL, 1, 18, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem7, 1, 23, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem8, 1, 8, 1, 1)
        self.TLevelL = QtWidgets.QLabel(self.Trigger)
        self.TLevelL.setObjectName("TLevelL")
        self.gridLayout_12.addWidget(self.TLevelL, 1, 15, 1, 1)
        self.TType = QtWidgets.QComboBox(self.Trigger)
        self.TType.setMinimumSize(QtCore.QSize(100, 0))
        self.TType.setMaximumSize(QtCore.QSize(100, 30))
        self.TType.setObjectName("TType")
        self.TType.addItem("")
        self.TType.addItem("")
        self.gridLayout_12.addWidget(self.TType, 1, 13, 1, 1)
        self.TActive = QtWidgets.QCheckBox(self.Trigger)
        self.TActive.setText("")
        self.TActive.setObjectName("TActive")
        self.gridLayout_12.addWidget(self.TActive, 1, 4, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem9, 1, 20, 1, 1)
        self.AutotriggerL = QtWidgets.QLabel(self.Trigger)
        self.AutotriggerL.setObjectName("AutotriggerL")
        self.gridLayout_12.addWidget(self.AutotriggerL, 1, 24, 1, 1)
        self.TChannelL = QtWidgets.QLabel(self.Trigger)
        self.TChannelL.setObjectName("TChannelL")
        self.gridLayout_12.addWidget(self.TChannelL, 1, 9, 1, 1)
        self.Autotrigger = QtWidgets.QLineEdit(self.Trigger)
        self.Autotrigger.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Autotrigger.setObjectName("Autotrigger")
        self.gridLayout_12.addWidget(self.Autotrigger, 1, 25, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem10, 1, 5, 1, 1)
        self.gridLayout_13.addWidget(self.Trigger, 1, 0, 1, 1)
        self.tabWidget.addTab(self.TimeSettings, "")
        self.ChannelSettings = QtWidgets.QWidget()
        self.ChannelSettings.setObjectName("ChannelSettings")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.ChannelSettings)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.ChannelB = QtWidgets.QGroupBox(self.ChannelSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ChannelB.sizePolicy().hasHeightForWidth())
        self.ChannelB.setSizePolicy(sizePolicy)
        self.ChannelB.setObjectName("ChannelB")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.ChannelB)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem11, 1, 2, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem12, 1, 5, 1, 1)
        self.BRangeL = QtWidgets.QLabel(self.ChannelB)
        self.BRangeL.setObjectName("BRangeL")
        self.gridLayout_2.addWidget(self.BRangeL, 1, 3, 1, 1)
        self.BNameL = QtWidgets.QLabel(self.ChannelB)
        self.BNameL.setObjectName("BNameL")
        self.gridLayout_2.addWidget(self.BNameL, 1, 10, 1, 1)
        self.BRange = QtWidgets.QComboBox(self.ChannelB)
        self.BRange.setMinimumSize(QtCore.QSize(0, 30))
        self.BRange.setMaximumSize(QtCore.QSize(16777215, 30))
        self.BRange.setObjectName("BRange")
        self.BRange.addItem("")
        self.BRange.addItem("")
        self.BRange.addItem("")
        self.BRange.addItem("")
        self.BRange.addItem("")
        self.BRange.addItem("")
        self.BRange.addItem("")
        self.BRange.addItem("")
        self.BRange.addItem("")
        self.BRange.addItem("")
        self.BRange.addItem("")
        self.gridLayout_2.addWidget(self.BRange, 1, 4, 1, 1)
        self.BActiveL = QtWidgets.QLabel(self.ChannelB)
        self.BActiveL.setObjectName("BActiveL")
        self.gridLayout_2.addWidget(self.BActiveL, 1, 0, 1, 1)
        self.BCoupling = QtWidgets.QComboBox(self.ChannelB)
        self.BCoupling.setMaximumSize(QtCore.QSize(16777215, 30))
        self.BCoupling.setObjectName("BCoupling")
        self.BCoupling.addItem("")
        self.BCoupling.addItem("")
        self.gridLayout_2.addWidget(self.BCoupling, 1, 7, 1, 1)
        self.BActive = QtWidgets.QCheckBox(self.ChannelB)
        self.BActive.setEnabled(True)
        self.BActive.setText("")
        self.BActive.setTristate(False)
        self.BActive.setObjectName("BActive")
        self.gridLayout_2.addWidget(self.BActive, 1, 1, 1, 1)
        self.BCouplingL = QtWidgets.QLabel(self.ChannelB)
        self.BCouplingL.setObjectName("BCouplingL")
        self.gridLayout_2.addWidget(self.BCouplingL, 1, 6, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem13, 1, 8, 1, 1)
        self.BName = QtWidgets.QLineEdit(self.ChannelB)
        self.BName.setMaximumSize(QtCore.QSize(16777215, 30))
        self.BName.setText("")
        self.BName.setObjectName("BName")
        self.gridLayout_2.addWidget(self.BName, 1, 11, 1, 1)
        self.gridLayout_9.addWidget(self.ChannelB, 1, 0, 1, 1)
        self.ChannelA = QtWidgets.QGroupBox(self.ChannelSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ChannelA.sizePolicy().hasHeightForWidth())
        self.ChannelA.setSizePolicy(sizePolicy)
        self.ChannelA.setObjectName("ChannelA")
        self.gridLayout = QtWidgets.QGridLayout(self.ChannelA)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem14, 1, 2, 1, 1)
        self.AActive = QtWidgets.QCheckBox(self.ChannelA)
        self.AActive.setEnabled(True)
        self.AActive.setMinimumSize(QtCore.QSize(0, 0))
        self.AActive.setText("")
        self.AActive.setIconSize(QtCore.QSize(16, 25))
        self.AActive.setChecked(False)
        self.AActive.setTristate(False)
        self.AActive.setObjectName("AActive")
        self.gridLayout.addWidget(self.AActive, 1, 1, 1, 1)
        self.ACouplingL = QtWidgets.QLabel(self.ChannelA)
        self.ACouplingL.setObjectName("ACouplingL")
        self.gridLayout.addWidget(self.ACouplingL, 1, 6, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem15, 1, 5, 1, 1)
        self.ARange = QtWidgets.QComboBox(self.ChannelA)
        self.ARange.setMinimumSize(QtCore.QSize(0, 30))
        self.ARange.setMaximumSize(QtCore.QSize(100, 30))
        self.ARange.setObjectName("ARange")
        self.ARange.addItem("")
        self.ARange.addItem("")
        self.ARange.addItem("")
        self.ARange.addItem("")
        self.ARange.addItem("")
        self.ARange.addItem("")
        self.ARange.addItem("")
        self.ARange.addItem("")
        self.ARange.addItem("")
        self.ARange.addItem("")
        self.ARange.addItem("")
        self.gridLayout.addWidget(self.ARange, 1, 4, 1, 1)
        self.ACoupling = QtWidgets.QComboBox(self.ChannelA)
        self.ACoupling.setMaximumSize(QtCore.QSize(16777215, 30))
        self.ACoupling.setObjectName("ACoupling")
        self.ACoupling.addItem("")
        self.ACoupling.addItem("")
        self.gridLayout.addWidget(self.ACoupling, 1, 7, 1, 1)
        self.AActiveL = QtWidgets.QLabel(self.ChannelA)
        self.AActiveL.setObjectName("AActiveL")
        self.gridLayout.addWidget(self.AActiveL, 1, 0, 1, 1)
        self.ANameL = QtWidgets.QLabel(self.ChannelA)
        self.ANameL.setObjectName("ANameL")
        self.gridLayout.addWidget(self.ANameL, 1, 9, 1, 1)
        self.ARangeL = QtWidgets.QLabel(self.ChannelA)
        self.ARangeL.setObjectName("ARangeL")
        self.gridLayout.addWidget(self.ARangeL, 1, 3, 1, 1)
        self.AName = QtWidgets.QLineEdit(self.ChannelA)
        self.AName.setMaximumSize(QtCore.QSize(16777215, 30))
        self.AName.setText("")
        self.AName.setObjectName("AName")
        self.gridLayout.addWidget(self.AName, 1, 10, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem16, 1, 8, 1, 1)
        self.gridLayout_9.addWidget(self.ChannelA, 0, 0, 1, 1)
        self.ChannelC = QtWidgets.QGroupBox(self.ChannelSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ChannelC.sizePolicy().hasHeightForWidth())
        self.ChannelC.setSizePolicy(sizePolicy)
        self.ChannelC.setObjectName("ChannelC")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.ChannelC)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.CNameL = QtWidgets.QLabel(self.ChannelC)
        self.CNameL.setObjectName("CNameL")
        self.gridLayout_4.addWidget(self.CNameL, 1, 9, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem17, 1, 2, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem18, 1, 5, 1, 1)
        self.CActiveL = QtWidgets.QLabel(self.ChannelC)
        self.CActiveL.setObjectName("CActiveL")
        self.gridLayout_4.addWidget(self.CActiveL, 1, 0, 1, 1)
        self.CActive = QtWidgets.QCheckBox(self.ChannelC)
        self.CActive.setEnabled(True)
        self.CActive.setText("")
        self.CActive.setTristate(False)
        self.CActive.setObjectName("CActive")
        self.gridLayout_4.addWidget(self.CActive, 1, 1, 1, 1)
        self.CCouplingL = QtWidgets.QLabel(self.ChannelC)
        self.CCouplingL.setObjectName("CCouplingL")
        self.gridLayout_4.addWidget(self.CCouplingL, 1, 6, 1, 1)
        self.CRange = QtWidgets.QComboBox(self.ChannelC)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CRange.sizePolicy().hasHeightForWidth())
        self.CRange.setSizePolicy(sizePolicy)
        self.CRange.setMinimumSize(QtCore.QSize(80, 30))
        self.CRange.setMaximumSize(QtCore.QSize(16777215, 30))
        self.CRange.setObjectName("CRange")
        self.CRange.addItem("")
        self.CRange.addItem("")
        self.CRange.addItem("")
        self.CRange.addItem("")
        self.CRange.addItem("")
        self.CRange.addItem("")
        self.CRange.addItem("")
        self.CRange.addItem("")
        self.CRange.addItem("")
        self.CRange.addItem("")
        self.CRange.addItem("")
        self.gridLayout_4.addWidget(self.CRange, 1, 4, 1, 1)
        self.CRangeL = QtWidgets.QLabel(self.ChannelC)
        self.CRangeL.setObjectName("CRangeL")
        self.gridLayout_4.addWidget(self.CRangeL, 1, 3, 1, 1)
        self.CCoupling = QtWidgets.QComboBox(self.ChannelC)
        self.CCoupling.setMaximumSize(QtCore.QSize(16777215, 30))
        self.CCoupling.setObjectName("CCoupling")
        self.CCoupling.addItem("")
        self.CCoupling.addItem("")
        self.gridLayout_4.addWidget(self.CCoupling, 1, 7, 1, 1)
        self.CName = QtWidgets.QLineEdit(self.ChannelC)
        self.CName.setMaximumSize(QtCore.QSize(16777215, 30))
        self.CName.setText("")
        self.CName.setObjectName("CName")
        self.gridLayout_4.addWidget(self.CName, 1, 10, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem19, 1, 8, 1, 1)
        self.gridLayout_9.addWidget(self.ChannelC, 0, 1, 1, 1)
        self.ChannelD = QtWidgets.QGroupBox(self.ChannelSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ChannelD.sizePolicy().hasHeightForWidth())
        self.ChannelD.setSizePolicy(sizePolicy)
        self.ChannelD.setObjectName("ChannelD")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.ChannelD)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.DRange = QtWidgets.QComboBox(self.ChannelD)
        self.DRange.setMinimumSize(QtCore.QSize(80, 30))
        self.DRange.setMaximumSize(QtCore.QSize(16777215, 30))
        self.DRange.setObjectName("DRange")
        self.DRange.addItem("")
        self.DRange.addItem("")
        self.DRange.addItem("")
        self.DRange.addItem("")
        self.DRange.addItem("")
        self.DRange.addItem("")
        self.DRange.addItem("")
        self.DRange.addItem("")
        self.DRange.addItem("")
        self.DRange.addItem("")
        self.DRange.addItem("")
        self.gridLayout_5.addWidget(self.DRange, 1, 4, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem20, 1, 5, 1, 1)
        self.DActive = QtWidgets.QCheckBox(self.ChannelD)
        self.DActive.setEnabled(True)
        self.DActive.setText("")
        self.DActive.setTristate(False)
        self.DActive.setObjectName("DActive")
        self.gridLayout_5.addWidget(self.DActive, 1, 1, 1, 1)
        self.DCouplingL = QtWidgets.QLabel(self.ChannelD)
        self.DCouplingL.setObjectName("DCouplingL")
        self.gridLayout_5.addWidget(self.DCouplingL, 1, 6, 1, 1)
        self.DRangeL = QtWidgets.QLabel(self.ChannelD)
        self.DRangeL.setObjectName("DRangeL")
        self.gridLayout_5.addWidget(self.DRangeL, 1, 3, 1, 1)
        self.DNameL = QtWidgets.QLabel(self.ChannelD)
        self.DNameL.setObjectName("DNameL")
        self.gridLayout_5.addWidget(self.DNameL, 1, 10, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem21, 1, 2, 1, 1)
        self.DActiveL = QtWidgets.QLabel(self.ChannelD)
        self.DActiveL.setObjectName("DActiveL")
        self.gridLayout_5.addWidget(self.DActiveL, 1, 0, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem22, 1, 9, 1, 1)
        self.DCoupling = QtWidgets.QComboBox(self.ChannelD)
        self.DCoupling.setMaximumSize(QtCore.QSize(16777215, 30))
        self.DCoupling.setObjectName("DCoupling")
        self.DCoupling.addItem("")
        self.DCoupling.addItem("")
        self.gridLayout_5.addWidget(self.DCoupling, 1, 7, 1, 1)
        self.DName = QtWidgets.QLineEdit(self.ChannelD)
        self.DName.setMaximumSize(QtCore.QSize(16777215, 30))
        self.DName.setText("")
        self.DName.setObjectName("DName")
        self.gridLayout_5.addWidget(self.DName, 1, 11, 1, 1)
        self.gridLayout_9.addWidget(self.ChannelD, 1, 1, 1, 1)
        self.tabWidget.addTab(self.ChannelSettings, "")
        self.Measure = QtWidgets.QWidget()
        self.Measure.setObjectName("Measure")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.Measure)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.Average = QtWidgets.QGroupBox(self.Measure)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Average.sizePolicy().hasHeightForWidth())
        self.Average.setSizePolicy(sizePolicy)
        self.Average.setObjectName("Average")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.Average)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.NumberOfMeasurementsL = QtWidgets.QLabel(self.Average)
        self.NumberOfMeasurementsL.setObjectName("NumberOfMeasurementsL")
        self.gridLayout_14.addWidget(self.NumberOfMeasurementsL, 1, 3, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem23, 1, 5, 1, 1)
        self.Pause = QtWidgets.QLineEdit(self.Average)
        self.Pause.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Pause.setText("")
        self.Pause.setObjectName("Pause")
        self.gridLayout_14.addWidget(self.Pause, 1, 7, 1, 1)
        self.NumberOfMeasurements = QtWidgets.QLineEdit(self.Average)
        self.NumberOfMeasurements.setMinimumSize(QtCore.QSize(0, 30))
        self.NumberOfMeasurements.setMaximumSize(QtCore.QSize(16777215, 30))
        self.NumberOfMeasurements.setText("")
        self.NumberOfMeasurements.setObjectName("NumberOfMeasurements")
        self.gridLayout_14.addWidget(self.NumberOfMeasurements, 1, 4, 1, 1)
        self.PauseL = QtWidgets.QLabel(self.Average)
        self.PauseL.setObjectName("PauseL")
        self.gridLayout_14.addWidget(self.PauseL, 1, 6, 1, 1)
        self.gridLayout_6.addWidget(self.Average, 1, 1, 1, 1)
        self.Plot = QtWidgets.QGroupBox(self.Measure)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Plot.sizePolicy().hasHeightForWidth())
        self.Plot.setSizePolicy(sizePolicy)
        self.Plot.setObjectName("Plot")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.Plot)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.ShowPlotL = QtWidgets.QLabel(self.Plot)
        self.ShowPlotL.setObjectName("ShowPlotL")
        self.gridLayout_19.addWidget(self.ShowPlotL, 1, 0, 1, 1)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem24, 1, 2, 1, 1)
        self.Save_plot_button = QtWidgets.QPushButton(self.Plot)
        self.Save_plot_button.setMinimumSize(QtCore.QSize(0, 30))
        self.Save_plot_button.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Save_plot_button.setObjectName("Save_plot_button")
        self.gridLayout_19.addWidget(self.Save_plot_button, 1, 4, 1, 1)
        self.ShowPlot = QtWidgets.QCheckBox(self.Plot)
        self.ShowPlot.setText("")
        self.ShowPlot.setObjectName("ShowPlot")
        self.gridLayout_19.addWidget(self.ShowPlot, 1, 1, 1, 1)
        self.gridLayout_6.addWidget(self.Plot, 2, 1, 1, 1)
        self.tabWidget.addTab(self.Measure, "")
        self.Analyse = QtWidgets.QWidget()
        self.Analyse.setObjectName("Analyse")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Analyse)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Analysis = QtWidgets.QGroupBox(self.Analyse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Analysis.sizePolicy().hasHeightForWidth())
        self.Analysis.setSizePolicy(sizePolicy)
        self.Analysis.setObjectName("Analysis")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.Analysis)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.ActivePL = QtWidgets.QLabel(self.Analysis)
        self.ActivePL.setObjectName("ActivePL")
        self.gridLayout_18.addWidget(self.ActivePL, 1, 0, 1, 1)
        self.NumberOfScans = QtWidgets.QLineEdit(self.Analysis)
        self.NumberOfScans.setMinimumSize(QtCore.QSize(0, 30))
        self.NumberOfScans.setMaximumSize(QtCore.QSize(16777215, 30))
        self.NumberOfScans.setText("")
        self.NumberOfScans.setObjectName("NumberOfScans")
        self.gridLayout_18.addWidget(self.NumberOfScans, 1, 5, 1, 1)
        self.ScanPause = QtWidgets.QLineEdit(self.Analysis)
        self.ScanPause.setMaximumSize(QtCore.QSize(16777215, 30))
        self.ScanPause.setText("")
        self.ScanPause.setObjectName("ScanPause")
        self.gridLayout_18.addWidget(self.ScanPause, 1, 8, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem25, 1, 6, 1, 1)
        self.NumberOfScansL = QtWidgets.QLabel(self.Analysis)
        self.NumberOfScansL.setObjectName("NumberOfScansL")
        self.gridLayout_18.addWidget(self.NumberOfScansL, 1, 4, 1, 1)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem26, 1, 3, 1, 1)
        self.AnalysisActive = QtWidgets.QCheckBox(self.Analysis)
        self.AnalysisActive.setText("")
        self.AnalysisActive.setObjectName("AnalysisActive")
        self.gridLayout_18.addWidget(self.AnalysisActive, 1, 1, 1, 1)
        self.ScanPauseL = QtWidgets.QLabel(self.Analysis)
        self.ScanPauseL.setObjectName("ScanPauseL")
        self.gridLayout_18.addWidget(self.ScanPauseL, 1, 7, 1, 1)
        self.verticalLayout_2.addWidget(self.Analysis)
        self.Window = QtWidgets.QGroupBox(self.Analyse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Window.sizePolicy().hasHeightForWidth())
        self.Window.setSizePolicy(sizePolicy)
        self.Window.setObjectName("Window")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.Window)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.WindowSelect = QtWidgets.QComboBox(self.Window)
        self.WindowSelect.setMinimumSize(QtCore.QSize(120, 30))
        self.WindowSelect.setMaximumSize(QtCore.QSize(120, 30))
        self.WindowSelect.setObjectName("WindowSelect")
        self.WindowSelect.addItem("")
        self.gridLayout_17.addWidget(self.WindowSelect, 1, 0, 1, 1)
        self.WindowStart = QtWidgets.QLineEdit(self.Window)
        self.WindowStart.setMaximumSize(QtCore.QSize(16777215, 30))
        self.WindowStart.setText("")
        self.WindowStart.setObjectName("WindowStart")
        self.gridLayout_17.addWidget(self.WindowStart, 1, 15, 1, 1)
        self.WindowShow = QtWidgets.QCheckBox(self.Window)
        self.WindowShow.setText("")
        self.WindowShow.setObjectName("WindowShow")
        self.gridLayout_17.addWidget(self.WindowShow, 1, 8, 1, 1)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem27, 1, 19, 1, 1)
        self.WindowLength = QtWidgets.QLineEdit(self.Window)
        self.WindowLength.setMaximumSize(QtCore.QSize(16777215, 30))
        self.WindowLength.setText("")
        self.WindowLength.setObjectName("WindowLength")
        self.gridLayout_17.addWidget(self.WindowLength, 1, 18, 1, 1)
        self.WindowShowL = QtWidgets.QLabel(self.Window)
        self.WindowShowL.setObjectName("WindowShowL")
        self.gridLayout_17.addWidget(self.WindowShowL, 1, 7, 1, 1)
        spacerItem28 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem28, 1, 1, 1, 1)
        self.WindowLengthL = QtWidgets.QLabel(self.Window)
        self.WindowLengthL.setObjectName("WindowLengthL")
        self.gridLayout_17.addWidget(self.WindowLengthL, 1, 17, 1, 1)
        self.WindowChannelL = QtWidgets.QLabel(self.Window)
        self.WindowChannelL.setObjectName("WindowChannelL")
        self.gridLayout_17.addWidget(self.WindowChannelL, 1, 10, 1, 1)
        self.WindowStartL = QtWidgets.QLabel(self.Window)
        self.WindowStartL.setObjectName("WindowStartL")
        self.gridLayout_17.addWidget(self.WindowStartL, 1, 14, 1, 1)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem29, 1, 16, 1, 1)
        self.WindowColourL = QtWidgets.QLabel(self.Window)
        self.WindowColourL.setObjectName("WindowColourL")
        self.gridLayout_17.addWidget(self.WindowColourL, 1, 4, 1, 1)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem30, 1, 12, 1, 1)
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem31, 1, 9, 1, 1)
        self.WindowDelete = QtWidgets.QPushButton(self.Window)
        self.WindowDelete.setMinimumSize(QtCore.QSize(0, 30))
        self.WindowDelete.setMaximumSize(QtCore.QSize(16777215, 30))
        self.WindowDelete.setObjectName("WindowDelete")
        self.gridLayout_17.addWidget(self.WindowDelete, 1, 20, 1, 1)
        self.WindowChannel = QtWidgets.QComboBox(self.Window)
        self.WindowChannel.setMinimumSize(QtCore.QSize(100, 30))
        self.WindowChannel.setMaximumSize(QtCore.QSize(100, 30))
        self.WindowChannel.setObjectName("WindowChannel")
        self.WindowChannel.addItem("")
        self.WindowChannel.addItem("")
        self.WindowChannel.addItem("")
        self.WindowChannel.addItem("")
        self.gridLayout_17.addWidget(self.WindowChannel, 1, 11, 1, 1)
        spacerItem32 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem32, 1, 6, 1, 1)
        self.WindowColour = QtWidgets.QPushButton(self.Window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WindowColour.sizePolicy().hasHeightForWidth())
        self.WindowColour.setSizePolicy(sizePolicy)
        self.WindowColour.setMinimumSize(QtCore.QSize(30, 30))
        self.WindowColour.setMaximumSize(QtCore.QSize(30, 30))
        self.WindowColour.setText("")
        self.WindowColour.setObjectName("WindowColour")
        self.gridLayout_17.addWidget(self.WindowColour, 1, 5, 1, 1)
        self.verticalLayout_2.addWidget(self.Window)
        self.Calculator = QtWidgets.QGroupBox(self.Analyse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Calculator.sizePolicy().hasHeightForWidth())
        self.Calculator.setSizePolicy(sizePolicy)
        self.Calculator.setObjectName("Calculator")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.Calculator)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.Operation = QtWidgets.QComboBox(self.Calculator)
        self.Operation.setMinimumSize(QtCore.QSize(40, 30))
        self.Operation.setMaximumSize(QtCore.QSize(40, 16777215))
        self.Operation.setObjectName("Operation")
        self.Operation.addItem("")
        self.Operation.addItem("")
        self.gridLayout_16.addWidget(self.Operation, 2, 13, 1, 1)
        spacerItem33 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem33, 2, 1, 1, 1)
        self.CalculatorShow = QtWidgets.QCheckBox(self.Calculator)
        self.CalculatorShow.setText("")
        self.CalculatorShow.setObjectName("CalculatorShow")
        self.gridLayout_16.addWidget(self.CalculatorShow, 2, 8, 1, 1)
        self.CalculatorSelect = QtWidgets.QComboBox(self.Calculator)
        self.CalculatorSelect.setMinimumSize(QtCore.QSize(120, 30))
        self.CalculatorSelect.setObjectName("CalculatorSelect")
        self.CalculatorSelect.addItem("")
        self.gridLayout_16.addWidget(self.CalculatorSelect, 2, 0, 1, 1)
        spacerItem34 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem34, 2, 5, 1, 1)
        self.SecondWindow = QtWidgets.QComboBox(self.Calculator)
        self.SecondWindow.setMinimumSize(QtCore.QSize(120, 30))
        self.SecondWindow.setObjectName("SecondWindow")
        self.gridLayout_16.addWidget(self.SecondWindow, 2, 14, 1, 1)
        self.CalculatorName = QtWidgets.QLineEdit(self.Calculator)
        self.CalculatorName.setMaximumSize(QtCore.QSize(16777215, 30))
        self.CalculatorName.setText("")
        self.CalculatorName.setObjectName("CalculatorName")
        self.gridLayout_16.addWidget(self.CalculatorName, 2, 18, 1, 1)
        self.FirstWindow = QtWidgets.QComboBox(self.Calculator)
        self.FirstWindow.setMinimumSize(QtCore.QSize(120, 30))
        self.FirstWindow.setCurrentText("")
        self.FirstWindow.setObjectName("FirstWindow")
        self.gridLayout_16.addWidget(self.FirstWindow, 2, 12, 1, 1)
        self.CalculatorDelete = QtWidgets.QPushButton(self.Calculator)
        self.CalculatorDelete.setMinimumSize(QtCore.QSize(0, 30))
        self.CalculatorDelete.setMaximumSize(QtCore.QSize(16777215, 30))
        self.CalculatorDelete.setObjectName("CalculatorDelete")
        self.gridLayout_16.addWidget(self.CalculatorDelete, 2, 20, 1, 1)
        self.CalculatorNameL = QtWidgets.QLabel(self.Calculator)
        self.CalculatorNameL.setObjectName("CalculatorNameL")
        self.gridLayout_16.addWidget(self.CalculatorNameL, 2, 16, 1, 1)
        self.CalculatorColour = QtWidgets.QPushButton(self.Calculator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CalculatorColour.sizePolicy().hasHeightForWidth())
        self.CalculatorColour.setSizePolicy(sizePolicy)
        self.CalculatorColour.setMinimumSize(QtCore.QSize(30, 30))
        self.CalculatorColour.setMaximumSize(QtCore.QSize(30, 30))
        self.CalculatorColour.setText("")
        self.CalculatorColour.setObjectName("CalculatorColour")
        self.gridLayout_16.addWidget(self.CalculatorColour, 2, 4, 1, 1)
        self.CalculatorShowL = QtWidgets.QLabel(self.Calculator)
        self.CalculatorShowL.setObjectName("CalculatorShowL")
        self.gridLayout_16.addWidget(self.CalculatorShowL, 2, 7, 1, 1)
        spacerItem35 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem35, 2, 9, 1, 1)
        spacerItem36 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem36, 2, 19, 1, 1)
        self.CalculatorColourL = QtWidgets.QLabel(self.Calculator)
        self.CalculatorColourL.setObjectName("CalculatorColourL")
        self.gridLayout_16.addWidget(self.CalculatorColourL, 2, 2, 1, 1)
        spacerItem37 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem37, 2, 15, 1, 1)
        self.verticalLayout_2.addWidget(self.Calculator)
        self.Scans = QtWidgets.QGroupBox(self.Analyse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Scans.sizePolicy().hasHeightForWidth())
        self.Scans.setSizePolicy(sizePolicy)
        self.Scans.setObjectName("Scans")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.Scans)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.ScnalLabelL = QtWidgets.QLabel(self.Scans)
        self.ScnalLabelL.setObjectName("ScnalLabelL")
        self.gridLayout_15.addWidget(self.ScnalLabelL, 1, 9, 1, 1)
        self.ScanLabel = QtWidgets.QLineEdit(self.Scans)
        self.ScanLabel.setMinimumSize(QtCore.QSize(0, 30))
        self.ScanLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.ScanLabel.setText("")
        self.ScanLabel.setObjectName("ScanLabel")
        self.gridLayout_15.addWidget(self.ScanLabel, 1, 10, 1, 1)
        self.ScanVauleDifferenceL = QtWidgets.QLabel(self.Scans)
        self.ScanVauleDifferenceL.setObjectName("ScanVauleDifferenceL")
        self.gridLayout_15.addWidget(self.ScanVauleDifferenceL, 1, 6, 1, 1)
        self.ScanValueDifference = QtWidgets.QLineEdit(self.Scans)
        self.ScanValueDifference.setMaximumSize(QtCore.QSize(16777215, 30))
        self.ScanValueDifference.setText("")
        self.ScanValueDifference.setObjectName("ScanValueDifference")
        self.gridLayout_15.addWidget(self.ScanValueDifference, 1, 7, 1, 1)
        self.ShowScanPlot = QtWidgets.QCheckBox(self.Scans)
        self.ShowScanPlot.setText("")
        self.ShowScanPlot.setObjectName("ShowScanPlot")
        self.gridLayout_15.addWidget(self.ShowScanPlot, 1, 1, 1, 1)
        self.ShowScanPlotL = QtWidgets.QLabel(self.Scans)
        self.ShowScanPlotL.setObjectName("ShowScanPlotL")
        self.gridLayout_15.addWidget(self.ShowScanPlotL, 1, 0, 1, 1)
        self.ScanValue = QtWidgets.QLineEdit(self.Scans)
        self.ScanValue.setMaximumSize(QtCore.QSize(16777215, 30))
        self.ScanValue.setText("")
        self.ScanValue.setObjectName("ScanValue")
        self.gridLayout_15.addWidget(self.ScanValue, 1, 4, 1, 1)
        self.ScanValueL = QtWidgets.QLabel(self.Scans)
        self.ScanValueL.setObjectName("ScanValueL")
        self.gridLayout_15.addWidget(self.ScanValueL, 1, 3, 1, 1)
        spacerItem38 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem38, 1, 5, 1, 1)
        spacerItem39 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem39, 1, 2, 1, 1)
        spacerItem40 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem40, 1, 8, 1, 1)
        spacerItem41 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem41, 1, 11, 1, 1)
        self.Save_scan_plot_button = QtWidgets.QPushButton(self.Scans)
        self.Save_scan_plot_button.setMinimumSize(QtCore.QSize(0, 30))
        self.Save_scan_plot_button.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Save_scan_plot_button.setObjectName("Save_scan_plot_button")
        self.gridLayout_15.addWidget(self.Save_scan_plot_button, 1, 12, 1, 1)
        self.verticalLayout_2.addWidget(self.Scans)
        self.tabWidget.addTab(self.Analyse, "")
        self.DelayTab = QtWidgets.QWidget()
        self.DelayTab.setObjectName("DelayTab")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.DelayTab)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.DelayBorderB = QtWidgets.QGroupBox(self.DelayTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DelayBorderB.sizePolicy().hasHeightForWidth())
        self.DelayBorderB.setSizePolicy(sizePolicy)
        self.DelayBorderB.setObjectName("DelayBorderB")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.DelayBorderB)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.Delay_BL = QtWidgets.QLabel(self.DelayBorderB)
        self.Delay_BL.setObjectName("Delay_BL")
        self.gridLayout_22.addWidget(self.Delay_BL, 1, 0, 1, 1)
        self.From_B = QtWidgets.QComboBox(self.DelayBorderB)
        self.From_B.setMinimumSize(QtCore.QSize(0, 30))
        self.From_B.setMaximumSize(QtCore.QSize(100, 30))
        self.From_B.setObjectName("From_B")
        self.From_B.addItem("")
        self.From_B.addItem("")
        self.From_B.addItem("")
        self.From_B.addItem("")
        self.gridLayout_22.addWidget(self.From_B, 1, 5, 1, 1)
        spacerItem42 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_22.addItem(spacerItem42, 1, 3, 1, 1)
        self.Delay_B = QtWidgets.QLineEdit(self.DelayBorderB)
        self.Delay_B.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Delay_B.setText("")
        self.Delay_B.setObjectName("Delay_B")
        self.gridLayout_22.addWidget(self.Delay_B, 1, 1, 1, 1)
        self.From_BL = QtWidgets.QLabel(self.DelayBorderB)
        self.From_BL.setObjectName("From_BL")
        self.gridLayout_22.addWidget(self.From_BL, 1, 4, 1, 1)
        self.gridLayout_24.addWidget(self.DelayBorderB, 1, 3, 1, 1)
        self.DelayBorderC = QtWidgets.QGroupBox(self.DelayTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DelayBorderC.sizePolicy().hasHeightForWidth())
        self.DelayBorderC.setSizePolicy(sizePolicy)
        self.DelayBorderC.setObjectName("DelayBorderC")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.DelayBorderC)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.From_C = QtWidgets.QComboBox(self.DelayBorderC)
        self.From_C.setMinimumSize(QtCore.QSize(0, 30))
        self.From_C.setMaximumSize(QtCore.QSize(100, 30))
        self.From_C.setObjectName("From_C")
        self.From_C.addItem("")
        self.From_C.addItem("")
        self.From_C.addItem("")
        self.From_C.addItem("")
        self.gridLayout_20.addWidget(self.From_C, 1, 5, 1, 1)
        self.Delay_CL = QtWidgets.QLabel(self.DelayBorderC)
        self.Delay_CL.setObjectName("Delay_CL")
        self.gridLayout_20.addWidget(self.Delay_CL, 1, 0, 1, 1)
        spacerItem43 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_20.addItem(spacerItem43, 1, 3, 1, 1)
        self.From_CL = QtWidgets.QLabel(self.DelayBorderC)
        self.From_CL.setObjectName("From_CL")
        self.gridLayout_20.addWidget(self.From_CL, 1, 4, 1, 1)
        self.Delay_C = QtWidgets.QLineEdit(self.DelayBorderC)
        self.Delay_C.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Delay_C.setText("")
        self.Delay_C.setObjectName("Delay_C")
        self.gridLayout_20.addWidget(self.Delay_C, 1, 1, 1, 1)
        self.gridLayout_24.addWidget(self.DelayBorderC, 3, 3, 1, 1)
        self.DelayBorderD = QtWidgets.QGroupBox(self.DelayTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DelayBorderD.sizePolicy().hasHeightForWidth())
        self.DelayBorderD.setSizePolicy(sizePolicy)
        self.DelayBorderD.setObjectName("DelayBorderD")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.DelayBorderD)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.Delay_D = QtWidgets.QLineEdit(self.DelayBorderD)
        self.Delay_D.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Delay_D.setText("")
        self.Delay_D.setObjectName("Delay_D")
        self.gridLayout_23.addWidget(self.Delay_D, 1, 1, 1, 1)
        self.Delay_DL = QtWidgets.QLabel(self.DelayBorderD)
        self.Delay_DL.setObjectName("Delay_DL")
        self.gridLayout_23.addWidget(self.Delay_DL, 1, 0, 1, 1)
        self.From_D = QtWidgets.QComboBox(self.DelayBorderD)
        self.From_D.setMinimumSize(QtCore.QSize(0, 30))
        self.From_D.setMaximumSize(QtCore.QSize(100, 30))
        self.From_D.setObjectName("From_D")
        self.From_D.addItem("")
        self.From_D.addItem("")
        self.From_D.addItem("")
        self.From_D.addItem("")
        self.gridLayout_23.addWidget(self.From_D, 1, 5, 1, 1)
        self.From_DL = QtWidgets.QLabel(self.DelayBorderD)
        self.From_DL.setObjectName("From_DL")
        self.gridLayout_23.addWidget(self.From_DL, 1, 4, 1, 1)
        spacerItem44 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_23.addItem(spacerItem44, 1, 3, 1, 1)
        self.gridLayout_24.addWidget(self.DelayBorderD, 4, 3, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.TriggerExt = QtWidgets.QGroupBox(self.DelayTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TriggerExt.sizePolicy().hasHeightForWidth())
        self.TriggerExt.setSizePolicy(sizePolicy)
        self.TriggerExt.setObjectName("TriggerExt")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.TriggerExt)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Delay_Ext_trigger_modeL = QtWidgets.QLabel(self.TriggerExt)
        self.Delay_Ext_trigger_modeL.setObjectName("Delay_Ext_trigger_modeL")
        self.horizontalLayout_4.addWidget(self.Delay_Ext_trigger_modeL)
        self.Delay_Ext_trigger_mode = QtWidgets.QComboBox(self.TriggerExt)
        self.Delay_Ext_trigger_mode.setMinimumSize(QtCore.QSize(100, 30))
        self.Delay_Ext_trigger_mode.setMaximumSize(QtCore.QSize(100, 30))
        self.Delay_Ext_trigger_mode.setObjectName("Delay_Ext_trigger_mode")
        self.Delay_Ext_trigger_mode.addItem("")
        self.Delay_Ext_trigger_mode.addItem("")
        self.horizontalLayout_4.addWidget(self.Delay_Ext_trigger_mode)
        spacerItem45 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem45)
        self.Delay_trigger_loadL = QtWidgets.QLabel(self.TriggerExt)
        self.Delay_trigger_loadL.setObjectName("Delay_trigger_loadL")
        self.horizontalLayout_4.addWidget(self.Delay_trigger_loadL)
        self.Delay_trigger_load = QtWidgets.QComboBox(self.TriggerExt)
        self.Delay_trigger_load.setMinimumSize(QtCore.QSize(100, 30))
        self.Delay_trigger_load.setMaximumSize(QtCore.QSize(100, 30))
        self.Delay_trigger_load.setObjectName("Delay_trigger_load")
        self.Delay_trigger_load.addItem("")
        self.Delay_trigger_load.addItem("")
        self.horizontalLayout_4.addWidget(self.Delay_trigger_load)
        spacerItem46 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem46)
        self.Delay_trigger_edgeL = QtWidgets.QLabel(self.TriggerExt)
        self.Delay_trigger_edgeL.setObjectName("Delay_trigger_edgeL")
        self.horizontalLayout_4.addWidget(self.Delay_trigger_edgeL)
        self.Delay_trigger_edge = QtWidgets.QComboBox(self.TriggerExt)
        self.Delay_trigger_edge.setMinimumSize(QtCore.QSize(100, 30))
        self.Delay_trigger_edge.setMaximumSize(QtCore.QSize(100, 30))
        self.Delay_trigger_edge.setObjectName("Delay_trigger_edge")
        self.Delay_trigger_edge.addItem("")
        self.Delay_trigger_edge.addItem("")
        self.horizontalLayout_4.addWidget(self.Delay_trigger_edge)
        spacerItem47 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem47)
        self.Delay_trigger_levelL = QtWidgets.QLabel(self.TriggerExt)
        self.Delay_trigger_levelL.setObjectName("Delay_trigger_levelL")
        self.horizontalLayout_4.addWidget(self.Delay_trigger_levelL)
        self.Delay_trigger_level = QtWidgets.QLineEdit(self.TriggerExt)
        self.Delay_trigger_level.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Delay_trigger_level.setText("")
        self.Delay_trigger_level.setObjectName("Delay_trigger_level")
        self.horizontalLayout_4.addWidget(self.Delay_trigger_level)
        self.horizontalLayout_3.addWidget(self.TriggerExt)
        self.TriggerInt = QtWidgets.QGroupBox(self.DelayTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TriggerInt.sizePolicy().hasHeightForWidth())
        self.TriggerInt.setSizePolicy(sizePolicy)
        self.TriggerInt.setObjectName("TriggerInt")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.TriggerInt)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.Delay_Int_trigger_modeL = QtWidgets.QLabel(self.TriggerInt)
        self.Delay_Int_trigger_modeL.setObjectName("Delay_Int_trigger_modeL")
        self.horizontalLayout_6.addWidget(self.Delay_Int_trigger_modeL)
        self.Delay_Int_trigger_mode = QtWidgets.QComboBox(self.TriggerInt)
        self.Delay_Int_trigger_mode.setMinimumSize(QtCore.QSize(100, 30))
        self.Delay_Int_trigger_mode.setMaximumSize(QtCore.QSize(100, 30))
        self.Delay_Int_trigger_mode.setObjectName("Delay_Int_trigger_mode")
        self.Delay_Int_trigger_mode.addItem("")
        self.Delay_Int_trigger_mode.addItem("")
        self.horizontalLayout_6.addWidget(self.Delay_Int_trigger_mode)
        spacerItem48 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem48)
        self.Delay_trigger_rateL = QtWidgets.QLabel(self.TriggerInt)
        self.Delay_trigger_rateL.setObjectName("Delay_trigger_rateL")
        self.horizontalLayout_6.addWidget(self.Delay_trigger_rateL)
        self.Delay_trigger_rate = QtWidgets.QLineEdit(self.TriggerInt)
        self.Delay_trigger_rate.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Delay_trigger_rate.setText("")
        self.Delay_trigger_rate.setObjectName("Delay_trigger_rate")
        self.horizontalLayout_6.addWidget(self.Delay_trigger_rate)
        self.horizontalLayout_3.addWidget(self.TriggerInt)
        self.gridLayout_24.addLayout(self.horizontalLayout_3, 3, 0, 2, 1)
        self.DelayBorderA = QtWidgets.QGroupBox(self.DelayTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DelayBorderA.sizePolicy().hasHeightForWidth())
        self.DelayBorderA.setSizePolicy(sizePolicy)
        self.DelayBorderA.setObjectName("DelayBorderA")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.DelayBorderA)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.Delay_AL = QtWidgets.QLabel(self.DelayBorderA)
        self.Delay_AL.setObjectName("Delay_AL")
        self.gridLayout_21.addWidget(self.Delay_AL, 0, 0, 1, 1)
        spacerItem49 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_21.addItem(spacerItem49, 0, 3, 1, 1)
        self.From_AL = QtWidgets.QLabel(self.DelayBorderA)
        self.From_AL.setObjectName("From_AL")
        self.gridLayout_21.addWidget(self.From_AL, 0, 4, 1, 1)
        self.From_A = QtWidgets.QComboBox(self.DelayBorderA)
        self.From_A.setMinimumSize(QtCore.QSize(0, 30))
        self.From_A.setMaximumSize(QtCore.QSize(100, 30))
        self.From_A.setObjectName("From_A")
        self.From_A.addItem("")
        self.From_A.addItem("")
        self.From_A.addItem("")
        self.From_A.addItem("")
        self.gridLayout_21.addWidget(self.From_A, 0, 5, 1, 1)
        self.Delay_A = QtWidgets.QLineEdit(self.DelayBorderA)
        self.Delay_A.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Delay_A.setText("")
        self.Delay_A.setObjectName("Delay_A")
        self.gridLayout_21.addWidget(self.Delay_A, 0, 1, 1, 1)
        self.gridLayout_24.addWidget(self.DelayBorderA, 0, 3, 1, 1)
        self.DelaySignal = QtWidgets.QGroupBox(self.DelayTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DelaySignal.sizePolicy().hasHeightForWidth())
        self.DelaySignal.setSizePolicy(sizePolicy)
        self.DelaySignal.setObjectName("DelaySignal")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.DelaySignal)
        self.gridLayout_25.setObjectName("gridLayout_25")
        spacerItem50 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_25.addItem(spacerItem50, 0, 3, 1, 1)
        self.Delay_signal_loadL = QtWidgets.QLabel(self.DelaySignal)
        self.Delay_signal_loadL.setObjectName("Delay_signal_loadL")
        self.gridLayout_25.addWidget(self.Delay_signal_loadL, 0, 4, 1, 1)
        self.Delay_signal_load = QtWidgets.QComboBox(self.DelaySignal)
        self.Delay_signal_load.setMinimumSize(QtCore.QSize(0, 30))
        self.Delay_signal_load.setMaximumSize(QtCore.QSize(100, 30))
        self.Delay_signal_load.setObjectName("Delay_signal_load")
        self.Delay_signal_load.addItem("")
        self.Delay_signal_load.addItem("")
        self.gridLayout_25.addWidget(self.Delay_signal_load, 0, 5, 1, 1)
        self.Delay_signal_type = QtWidgets.QComboBox(self.DelaySignal)
        self.Delay_signal_type.setMinimumSize(QtCore.QSize(100, 30))
        self.Delay_signal_type.setMaximumSize(QtCore.QSize(100, 30))
        self.Delay_signal_type.setObjectName("Delay_signal_type")
        self.Delay_signal_type.addItem("")
        self.Delay_signal_type.addItem("")
        self.Delay_signal_type.addItem("")
        self.gridLayout_25.addWidget(self.Delay_signal_type, 0, 1, 1, 1)
        self.Delay_signal_typeL = QtWidgets.QLabel(self.DelaySignal)
        self.Delay_signal_typeL.setObjectName("Delay_signal_typeL")
        self.gridLayout_25.addWidget(self.Delay_signal_typeL, 0, 0, 1, 1)
        self.gridLayout_24.addWidget(self.DelaySignal, 0, 0, 2, 1)
        self.tabWidget.addTab(self.DelayTab, "")
        self.gridLayout_3.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_3)
        self.gridLayout_10.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1795, 21))
        self.menubar.setObjectName("menubar")
        self.menuAdd_Device = QtWidgets.QMenu(self.menubar)
        self.menuAdd_Device.setObjectName("menuAdd_Device")
        self.menuSRS_Delay_Generator_535 = QtWidgets.QMenu(self.menuAdd_Device)
        self.menuSRS_Delay_Generator_535.setObjectName("menuSRS_Delay_Generator_535")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Save = QtWidgets.QAction(MainWindow)
        self.action_Save.setObjectName("action_Save")
        self.actionOpen_File = QtWidgets.QAction(MainWindow)
        self.actionOpen_File.setObjectName("actionOpen_File")
        self.action_Start = QtWidgets.QAction(MainWindow)
        self.action_Start.setObjectName("action_Start")
        self.action_Stop = QtWidgets.QAction(MainWindow)
        self.action_Stop.setObjectName("action_Stop")
        self.actionPicoScope5444D = QtWidgets.QAction(MainWindow)
        self.actionPicoScope5444D.setObjectName("actionPicoScope5444D")
        self.actionPicoScope5244D = QtWidgets.QAction(MainWindow)
        self.actionPicoScope5244D.setObjectName("actionPicoScope5244D")
        self.SRS_Connect = QtWidgets.QAction(MainWindow)
        self.SRS_Connect.setObjectName("SRS_Connect")
        self.SRS_Connect_and_Control = QtWidgets.QAction(MainWindow)
        self.SRS_Connect_and_Control.setObjectName("SRS_Connect_and_Control")
        self.SRS_Disconnect = QtWidgets.QAction(MainWindow)
        self.SRS_Disconnect.setObjectName("SRS_Disconnect")
        self.menuSRS_Delay_Generator_535.addAction(self.SRS_Connect)
        self.menuSRS_Delay_Generator_535.addAction(self.SRS_Disconnect)
        self.menuAdd_Device.addAction(self.menuSRS_Delay_Generator_535.menuAction())
        self.menubar.addAction(self.menuAdd_Device.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.start_button.setText(_translate("MainWindow", "Start"))
        self.continuously_button.setText(_translate("MainWindow", "Continuously"))
        self.pause_button.setText(_translate("MainWindow", "Pause"))
        self.stop_button.setText(_translate("MainWindow", "Stop"))
        self.Save_personal_settingsL.setText(_translate("MainWindow", "Save personal settings:"))
        self.ProjectL.setText(_translate("MainWindow", "Project:"))
        self.NameL.setText(_translate("MainWindow", "Name:"))
        self.FontsizeL.setText(_translate("MainWindow", "Fontsize:"))
        self.Save_personal_settings_button.setText(_translate("MainWindow", "Save"))
        self.Import_from_metadataL.setText(_translate("MainWindow", "Import from metadata:"))
        self.Import_personal_settings_metadata_button.setText(_translate("MainWindow", "Import"))
        self.Load_personal_settings_button.setText(_translate("MainWindow", "Load"))
        self.Load_personal_settingsL.setText(_translate("MainWindow", "Load personal settings:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.User), _translate("MainWindow", "User"))
        self.DirectoryL.setText(_translate("MainWindow", "Directory:"))
        self.FilenameL.setText(_translate("MainWindow", "Filename:"))
        self.Autosave.setItemText(0, _translate("MainWindow", "Never"))
        self.Autosave.setItemText(1, _translate("MainWindow", "Every scope"))
        self.Autosave.setItemText(2, _translate("MainWindow", "Every scope average"))
        self.AutosaveL.setText(_translate("MainWindow", "Save data:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Save), _translate("MainWindow", "Save"))
        self.Time.setTitle(_translate("MainWindow", "Resolution"))
        self.BlocklengthL.setText(_translate("MainWindow", "Blocklength:"))
        self.ResolutionL.setText(_translate("MainWindow", "Resolution:"))
        self.SamplesL.setText(_translate("MainWindow", "Samples:"))
        self.Resolution.setItemText(0, _translate("MainWindow", "8BIT"))
        self.Resolution.setItemText(1, _translate("MainWindow", "12BIT"))
        self.Resolution.setItemText(2, _translate("MainWindow", "14BIT"))
        self.Resolution.setItemText(3, _translate("MainWindow", "15BIT"))
        self.Resolution.setItemText(4, _translate("MainWindow", "16BIT"))
        self.TimestepL.setText(_translate("MainWindow", "Timestep:"))
        self.Trigger.setTitle(_translate("MainWindow", "Trigger"))
        self.TAtiveL_2.setText(_translate("MainWindow", "Show:"))
        self.TChannelL_2.setText(_translate("MainWindow", "Edge:"))
        self.TSampleInWindowL.setText(_translate("MainWindow", "Sample position:"))
        self.TAtiveL.setText(_translate("MainWindow", "Active:"))
        self.TChannel.setItemText(0, _translate("MainWindow", "External"))
        self.TChannel.setItemText(1, _translate("MainWindow", "A"))
        self.TChannel.setItemText(2, _translate("MainWindow", "B"))
        self.TChannel.setItemText(3, _translate("MainWindow", "C"))
        self.TChannel.setItemText(4, _translate("MainWindow", "D"))
        self.TSamplesDelayedL.setText(_translate("MainWindow", "Samples Delayed:"))
        self.TLevelL.setText(_translate("MainWindow", "Level:"))
        self.TType.setItemText(0, _translate("MainWindow", "Rising"))
        self.TType.setItemText(1, _translate("MainWindow", "Falling"))
        self.AutotriggerL.setText(_translate("MainWindow", "Autotrigger after:"))
        self.TChannelL.setText(_translate("MainWindow", "Channel:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TimeSettings), _translate("MainWindow", "Time"))
        self.ChannelB.setTitle(_translate("MainWindow", "B"))
        self.BRangeL.setText(_translate("MainWindow", "Range:"))
        self.BNameL.setText(_translate("MainWindow", "Name:"))
        self.BRange.setCurrentText(_translate("MainWindow", "10 mV"))
        self.BRange.setItemText(0, _translate("MainWindow", "10 mV"))
        self.BRange.setItemText(1, _translate("MainWindow", "20 mV"))
        self.BRange.setItemText(2, _translate("MainWindow", "50 mV"))
        self.BRange.setItemText(3, _translate("MainWindow", "100 mV"))
        self.BRange.setItemText(4, _translate("MainWindow", "200 mV"))
        self.BRange.setItemText(5, _translate("MainWindow", "500 mV"))
        self.BRange.setItemText(6, _translate("MainWindow", "1 V"))
        self.BRange.setItemText(7, _translate("MainWindow", "2 V"))
        self.BRange.setItemText(8, _translate("MainWindow", "5 V"))
        self.BRange.setItemText(9, _translate("MainWindow", "10 V"))
        self.BRange.setItemText(10, _translate("MainWindow", "20 V"))
        self.BActiveL.setText(_translate("MainWindow", "Active:"))
        self.BCoupling.setCurrentText(_translate("MainWindow", "DC"))
        self.BCoupling.setItemText(0, _translate("MainWindow", "DC"))
        self.BCoupling.setItemText(1, _translate("MainWindow", "AC"))
        self.BCouplingL.setText(_translate("MainWindow", "Coupling:"))
        self.ChannelA.setTitle(_translate("MainWindow", "A"))
        self.ACouplingL.setText(_translate("MainWindow", "Coupling:"))
        self.ARange.setCurrentText(_translate("MainWindow", "10 mV"))
        self.ARange.setItemText(0, _translate("MainWindow", "10 mV"))
        self.ARange.setItemText(1, _translate("MainWindow", "20 mV"))
        self.ARange.setItemText(2, _translate("MainWindow", "50 mV"))
        self.ARange.setItemText(3, _translate("MainWindow", "100 mV"))
        self.ARange.setItemText(4, _translate("MainWindow", "200 mV"))
        self.ARange.setItemText(5, _translate("MainWindow", "500 mV"))
        self.ARange.setItemText(6, _translate("MainWindow", "1 V"))
        self.ARange.setItemText(7, _translate("MainWindow", "2 V"))
        self.ARange.setItemText(8, _translate("MainWindow", "5 V"))
        self.ARange.setItemText(9, _translate("MainWindow", "10 V"))
        self.ARange.setItemText(10, _translate("MainWindow", "20 V"))
        self.ACoupling.setCurrentText(_translate("MainWindow", "DC"))
        self.ACoupling.setItemText(0, _translate("MainWindow", "DC"))
        self.ACoupling.setItemText(1, _translate("MainWindow", "AC"))
        self.AActiveL.setText(_translate("MainWindow", "Active:"))
        self.ANameL.setText(_translate("MainWindow", "Name:"))
        self.ARangeL.setText(_translate("MainWindow", "Range:"))
        self.ChannelC.setTitle(_translate("MainWindow", "C"))
        self.CNameL.setText(_translate("MainWindow", "Name:"))
        self.CActiveL.setText(_translate("MainWindow", "Active:"))
        self.CCouplingL.setText(_translate("MainWindow", "Coupling:"))
        self.CRange.setCurrentText(_translate("MainWindow", "10 mV"))
        self.CRange.setItemText(0, _translate("MainWindow", "10 mV"))
        self.CRange.setItemText(1, _translate("MainWindow", "20 mV"))
        self.CRange.setItemText(2, _translate("MainWindow", "50 mV"))
        self.CRange.setItemText(3, _translate("MainWindow", "100 mV"))
        self.CRange.setItemText(4, _translate("MainWindow", "200 mV"))
        self.CRange.setItemText(5, _translate("MainWindow", "500 mV"))
        self.CRange.setItemText(6, _translate("MainWindow", "1 V"))
        self.CRange.setItemText(7, _translate("MainWindow", "2 V"))
        self.CRange.setItemText(8, _translate("MainWindow", "5 V"))
        self.CRange.setItemText(9, _translate("MainWindow", "10 V"))
        self.CRange.setItemText(10, _translate("MainWindow", "20 V"))
        self.CRangeL.setText(_translate("MainWindow", "Range:"))
        self.CCoupling.setCurrentText(_translate("MainWindow", "DC"))
        self.CCoupling.setItemText(0, _translate("MainWindow", "DC"))
        self.CCoupling.setItemText(1, _translate("MainWindow", "AC"))
        self.ChannelD.setTitle(_translate("MainWindow", "D"))
        self.DRange.setCurrentText(_translate("MainWindow", "10 mV"))
        self.DRange.setItemText(0, _translate("MainWindow", "10 mV"))
        self.DRange.setItemText(1, _translate("MainWindow", "20 mV"))
        self.DRange.setItemText(2, _translate("MainWindow", "50 mV"))
        self.DRange.setItemText(3, _translate("MainWindow", "100 mV"))
        self.DRange.setItemText(4, _translate("MainWindow", "200 mV"))
        self.DRange.setItemText(5, _translate("MainWindow", "500 mV"))
        self.DRange.setItemText(6, _translate("MainWindow", "1 V"))
        self.DRange.setItemText(7, _translate("MainWindow", "2 V"))
        self.DRange.setItemText(8, _translate("MainWindow", "5 V"))
        self.DRange.setItemText(9, _translate("MainWindow", "10 V"))
        self.DRange.setItemText(10, _translate("MainWindow", "20 V"))
        self.DCouplingL.setText(_translate("MainWindow", "Coupling:"))
        self.DRangeL.setText(_translate("MainWindow", "Range:"))
        self.DNameL.setText(_translate("MainWindow", "Name:"))
        self.DActiveL.setText(_translate("MainWindow", "Active:"))
        self.DCoupling.setCurrentText(_translate("MainWindow", "DC"))
        self.DCoupling.setItemText(0, _translate("MainWindow", "DC"))
        self.DCoupling.setItemText(1, _translate("MainWindow", "AC"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ChannelSettings), _translate("MainWindow", "Channels"))
        self.Average.setTitle(_translate("MainWindow", "Average"))
        self.NumberOfMeasurementsL.setText(_translate("MainWindow", "Number of measurements:"))
        self.PauseL.setText(_translate("MainWindow", "Time between measurements:"))
        self.Plot.setTitle(_translate("MainWindow", "Plot"))
        self.ShowPlotL.setText(_translate("MainWindow", "Show:"))
        self.Save_plot_button.setText(_translate("MainWindow", "Save plot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Measure), _translate("MainWindow", "Scope"))
        self.Analysis.setTitle(_translate("MainWindow", "Scanpoints"))
        self.ActivePL.setText(_translate("MainWindow", "Active:"))
        self.NumberOfScansL.setText(_translate("MainWindow", "Number of scanpoints:"))
        self.ScanPauseL.setText(_translate("MainWindow", "Time between scanspoints:"))
        self.Window.setTitle(_translate("MainWindow", "Window"))
        self.WindowSelect.setCurrentText(_translate("MainWindow", "Add Window"))
        self.WindowSelect.setItemText(0, _translate("MainWindow", "Add Window"))
        self.WindowShowL.setText(_translate("MainWindow", "Show:"))
        self.WindowLengthL.setText(_translate("MainWindow", "Length:"))
        self.WindowChannelL.setText(_translate("MainWindow", "Channel:"))
        self.WindowStartL.setText(_translate("MainWindow", "Start:"))
        self.WindowColourL.setText(_translate("MainWindow", "Colour:"))
        self.WindowDelete.setText(_translate("MainWindow", "Delete"))
        self.WindowChannel.setItemText(0, _translate("MainWindow", "A"))
        self.WindowChannel.setItemText(1, _translate("MainWindow", "B"))
        self.WindowChannel.setItemText(2, _translate("MainWindow", "C"))
        self.WindowChannel.setItemText(3, _translate("MainWindow", "D"))
        self.Calculator.setTitle(_translate("MainWindow", "Calculator"))
        self.Operation.setItemText(0, _translate("MainWindow", "+"))
        self.Operation.setItemText(1, _translate("MainWindow", "-"))
        self.CalculatorSelect.setCurrentText(_translate("MainWindow", "Add Calculator"))
        self.CalculatorSelect.setItemText(0, _translate("MainWindow", "Add Calculator"))
        self.CalculatorDelete.setText(_translate("MainWindow", "Delete"))
        self.CalculatorNameL.setText(_translate("MainWindow", "Name:"))
        self.CalculatorShowL.setText(_translate("MainWindow", "Show:"))
        self.CalculatorColourL.setText(_translate("MainWindow", "Colour:"))
        self.Scans.setTitle(_translate("MainWindow", "Scanplot"))
        self.ScnalLabelL.setText(_translate("MainWindow", "Scanpoint label:"))
        self.ScanVauleDifferenceL.setText(_translate("MainWindow", "Scanpoint value difference:"))
        self.ShowScanPlotL.setText(_translate("MainWindow", "Show:"))
        self.ScanValueL.setText(_translate("MainWindow", "Scanpoint value:"))
        self.Save_scan_plot_button.setText(_translate("MainWindow", "Save plot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Analyse), _translate("MainWindow", "Scan"))
        self.DelayBorderB.setTitle(_translate("MainWindow", "B"))
        self.Delay_BL.setText(_translate("MainWindow", "Delay:"))
        self.From_B.setCurrentText(_translate("MainWindow", "T0"))
        self.From_B.setItemText(0, _translate("MainWindow", "T0"))
        self.From_B.setItemText(1, _translate("MainWindow", "A"))
        self.From_B.setItemText(2, _translate("MainWindow", "C"))
        self.From_B.setItemText(3, _translate("MainWindow", "D"))
        self.From_BL.setText(_translate("MainWindow", "From:"))
        self.DelayBorderC.setTitle(_translate("MainWindow", "C"))
        self.From_C.setCurrentText(_translate("MainWindow", "T0"))
        self.From_C.setItemText(0, _translate("MainWindow", "T0"))
        self.From_C.setItemText(1, _translate("MainWindow", "A"))
        self.From_C.setItemText(2, _translate("MainWindow", "B"))
        self.From_C.setItemText(3, _translate("MainWindow", "D"))
        self.Delay_CL.setText(_translate("MainWindow", "Delay:"))
        self.From_CL.setText(_translate("MainWindow", "From:"))
        self.DelayBorderD.setTitle(_translate("MainWindow", "D"))
        self.Delay_DL.setText(_translate("MainWindow", "Delay:"))
        self.From_D.setCurrentText(_translate("MainWindow", "T0"))
        self.From_D.setItemText(0, _translate("MainWindow", "T0"))
        self.From_D.setItemText(1, _translate("MainWindow", "A"))
        self.From_D.setItemText(2, _translate("MainWindow", "B"))
        self.From_D.setItemText(3, _translate("MainWindow", "C"))
        self.From_DL.setText(_translate("MainWindow", "From:"))
        self.TriggerExt.setTitle(_translate("MainWindow", "Trigger"))
        self.Delay_Ext_trigger_modeL.setText(_translate("MainWindow", "Mode:"))
        self.Delay_Ext_trigger_mode.setCurrentText(_translate("MainWindow", "Internal"))
        self.Delay_Ext_trigger_mode.setItemText(0, _translate("MainWindow", "Internal"))
        self.Delay_Ext_trigger_mode.setItemText(1, _translate("MainWindow", "External"))
        self.Delay_trigger_loadL.setText(_translate("MainWindow", "Load:"))
        self.Delay_trigger_load.setCurrentText(_translate("MainWindow", "50 Ohm"))
        self.Delay_trigger_load.setItemText(0, _translate("MainWindow", "50 Ohm"))
        self.Delay_trigger_load.setItemText(1, _translate("MainWindow", "HighZ"))
        self.Delay_trigger_edgeL.setText(_translate("MainWindow", "Edge:"))
        self.Delay_trigger_edge.setCurrentText(_translate("MainWindow", "Rising"))
        self.Delay_trigger_edge.setItemText(0, _translate("MainWindow", "Rising"))
        self.Delay_trigger_edge.setItemText(1, _translate("MainWindow", "Falling"))
        self.Delay_trigger_levelL.setText(_translate("MainWindow", "Level:"))
        self.TriggerInt.setTitle(_translate("MainWindow", "Trigger"))
        self.Delay_Int_trigger_modeL.setText(_translate("MainWindow", "Mode:"))
        self.Delay_Int_trigger_mode.setCurrentText(_translate("MainWindow", "Internal"))
        self.Delay_Int_trigger_mode.setItemText(0, _translate("MainWindow", "Internal"))
        self.Delay_Int_trigger_mode.setItemText(1, _translate("MainWindow", "External"))
        self.Delay_trigger_rateL.setText(_translate("MainWindow", "Rate:"))
        self.DelayBorderA.setTitle(_translate("MainWindow", "A"))
        self.Delay_AL.setText(_translate("MainWindow", "Delay:"))
        self.From_AL.setText(_translate("MainWindow", "From:"))
        self.From_A.setCurrentText(_translate("MainWindow", "T0"))
        self.From_A.setItemText(0, _translate("MainWindow", "T0"))
        self.From_A.setItemText(1, _translate("MainWindow", "B"))
        self.From_A.setItemText(2, _translate("MainWindow", "C"))
        self.From_A.setItemText(3, _translate("MainWindow", "D"))
        self.DelaySignal.setTitle(_translate("MainWindow", "Signal"))
        self.Delay_signal_loadL.setText(_translate("MainWindow", "Load:"))
        self.Delay_signal_load.setCurrentText(_translate("MainWindow", "50 Ohm"))
        self.Delay_signal_load.setItemText(0, _translate("MainWindow", "50 Ohm"))
        self.Delay_signal_load.setItemText(1, _translate("MainWindow", "HighZ"))
        self.Delay_signal_type.setCurrentText(_translate("MainWindow", "TTL"))
        self.Delay_signal_type.setItemText(0, _translate("MainWindow", "TTL"))
        self.Delay_signal_type.setItemText(1, _translate("MainWindow", "NIM"))
        self.Delay_signal_type.setItemText(2, _translate("MainWindow", "ECL"))
        self.Delay_signal_typeL.setText(_translate("MainWindow", "Type:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DelayTab), _translate("MainWindow", "Delay"))
        self.menuAdd_Device.setTitle(_translate("MainWindow", "Other devices"))
        self.menuSRS_Delay_Generator_535.setTitle(_translate("MainWindow", "SRS Delay Generator 535"))
        self.action_Save.setText(_translate("MainWindow", "&Save"))
        self.action_Save.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionOpen_File.setText(_translate("MainWindow", "Open File"))
        self.action_Start.setText(_translate("MainWindow", "Start"))
        self.action_Start.setShortcut(_translate("MainWindow", "Ctrl+B"))
        self.action_Stop.setText(_translate("MainWindow", "Stop"))
        self.action_Stop.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.actionPicoScope5444D.setText(_translate("MainWindow", "Max 4 channels"))
        self.actionPicoScope5244D.setText(_translate("MainWindow", "Max 2 channels"))
        self.SRS_Connect.setText(_translate("MainWindow", "Connect"))
        self.SRS_Connect_and_Control.setText(_translate("MainWindow", "Connect and Control"))
        self.SRS_Disconnect.setText(_translate("MainWindow", "Disconnect"))


